### ISSUE TITLE
Dark and light themes

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/quarto-revealjs-uaz#8]
Currently setting `theme: dark` makes the background black and `theme: light` results in an error.  Ideally these would be two different color themes, both UAZ official colors.  Not sure how to do this in SCSS yet.

**Comment by Aariq** [comment]
Hmm... I guess that's not how themes work.  I think I could just create additional custom themes inside of _extensions.  E.g. if I created a `uaz-light` directory, then I'd use it with `format: uaz-light-revealjs`.  Still would like to do this eventually.

**Comment by Aariq** [comment]
Looks like you can add a light/dark switch by providing two themes.
``` yaml
theme:
  light: flatly
  dark: darkly
```

and those can be customized.  E.g.: 

``` yaml

theme:
  light: cosmo
  dark: [cosmo, theme-dark.scss]

```
https://quarto.org/docs/output-formats/html-themes.html
